apiVersion: v1
kind: Pod
metadata:
  labels:
    name: offlinereporting
  name: offlinereporting
spec:
  volumes:
    - name: "tsdemo-data"
      emptyDir: {}
  containers:
    - image: mhausenblas/tsdemo-s3-fetcher
      name: s3-fetcher
      env:
         - name: AWS_ACCESS_KEY_ID
           value:
         - name: AWS_SECRET_ACCESS_KEY
           value:
      volumeMounts:
        - mountPath: "/tmp/tsdemo"
          name: "tsdemo-data"
      resources:
        limits:
          cpu: "800m"
          memory: "200Mi"
    - image: mhausenblas/tsdemo-offline-reporting-ui
      name: webui
      volumeMounts:
        - mountPath: "/tmp/tsdemo"
          name: "tsdemo-data"
          readOnly: true
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      resources:
        limits:
          cpu: "500m"
          memory: "100Mi"
