apiVersion: v1
kind: ReplicationController
metadata:
  name: offlinereporting-rc
spec:
  replicas: 1
  selector:
    name: offlinereporting
  template:
    metadata:
      labels:
        name: offlinereporting
    spec:
      volumes:
        - name: "tsdemo-data"
          emptyDir: {}
        - name: "tsdemo-cred"
          secret:
            secretName: awssecret
      containers:
        - image: mhausenblas/tsdemo-s3-fetcher
          imagePullPolicy: Always
          name: s3-fetcher
          volumeMounts:
            - mountPath: "/tmp/tsdemo"
              name: "tsdemo-data"
            - mountPath: "/tmp/aws"
              name: "tsdemo-cred"
          resources:
            limits:
              cpu: "800m"
              memory: "200Mi"
        - image: mhausenblas/tsdemo-offline-reporting-ui
          imagePullPolicy: Always
          name: webui
          volumeMounts:
            - mountPath: "/etc/nginx/html/data"
              name: "tsdemo-data"
              readOnly: false
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "100Mi"
